<?php

$minimalbmsthemearray = array (
    "crosscolor"  => "Grey",
    "crosscolorhover" => "Dark Grey",
	"selectorhovercolor"  => "#f2f2f2",
	"selectorcolor"  => "",
    "titletexte" => "",
	"titleborder"  => "#c6c6c6",
    "maincategorytexte" => "",
	"titleselectedcriteretexte"  => "",
    "selectedcriteretexte" => "",
	"criteretexte"  => "",
    "selectedcriteretextehover" => "",
	"selectedcriterehovercolor"  => "#e5e5e5",
	"selectedcriterebordercolor"  => "#c6c6c6",
    "cancelselectedcriteretexte" => "",
	"cancelselectedcriterebg" => "",
	"cancelselectedcritereborder" => "#c6c6c6",
	"critereborder" => "#c6c6c6",
	"selectorhoverbordercolor" => "#c6c6c6",
	"bulletsquare" => "yes",
	"bulletcircle" => "",
	"bulletsize" => "10",
	"qmcolor" => "Black",
	"noqm" => "",
	"qmbg" => "#c1c1c1",
	"qmradius" => "50",
	"qmsdx" => "2",
	"qmsdy" => "2",
	"qmsdcolor" => "#656565",
	"qmsd" => "on",
	"qmmt" => "10",
	"qmsdbdcolor" =>""
); 

$orangejuicebmsthemearray = array (
    "crosscolor"  => "Grey",
    "crosscolorhover" => "Dark Grey",
	"selectorhovercolor"  => "#FCBC87",
	"selectorcolor"  => "",
    "titletexte" => "#000",
	"titleborder"  => "#5b5b5b",
    "maincategorytexte" => "#f89039",
	"titleselectedcriteretexte"  => "",
    "selectedcriteretexte" => "#333",
	"criteretexte"  => "#97a5ae",
    "selectedcriteretextehover" => "#000",
	"selectedcriterehovercolor"  => "#F89039",
	"selectedcriterebordercolor"  => "#F89039",
    "cancelselectedcriteretexte" => "#97a5ae",
	"cancelselectedcriterebg" => "",
	"cancelselectedcritereborder" => "#F89039",
	"critereborder" => "#c6c6c6",
	"selectorhoverbordercolor" => "#f89039",
	"bulletsquare" => "yes",
	"bulletcircle" => "",
	"bulletsize" => "8",
	"qmcolor" => "White",
	"noqm" => "",
	"qmbg" => "#F89039",
	"qmradius" => "50",
	"qmsdx" => "2",
	"qmsdy" => "2",
	"qmsdcolor" => "#656565",
	"qmsd" => "on",
	"qmmt" => "10",
	"qmsdbdcolor" =>""
);

$orangejuicebmsethemearray = array (
	"atb_font_color" => "white",
	"atb_bg_color" => "#F89039",
	"atb_radius" => "2",
	"atb_margin_left" => "7",
	"atb_bg_color_hover" => "#5b5b5b",
	"atb_bg_border_color" => ""
);

$lemonzestbmsthemearray = array (
    "crosscolor"  => "Dark Grey",
	"crosscolorhover" => "White",
	"selectorhovercolor"  => "#d8d9d8",
	"selectorcolor"  => "",
    "titletexte" => "#000",
	"titleborder"  => "#c6c6c6",
    "maincategorytexte" => "",
	"titleselectedcriteretexte"  => "",
    "selectedcriteretexte" => "#232323",
	"criteretexte"  => "#97a5ae",
    "selectedcriteretextehover" => "#ffffff",
	"selectedcriterehovercolor"  => "#363635",
	"selectedcriterebordercolor"  => "#c6c6c6",
    "cancelselectedcriteretexte" => "#ffffff",
	"cancelselectedcriterebg" => "#fec107",
	"cancelselectedcritereborder" => "#c6c6c6",
	"critereborder" => "#c6c6c6",
	"selectorhoverbordercolor" => "#c6c6c6",
	"bulletsquare" => "yes",
	"bulletcircle" => "",
	"bulletsize" => "10",
	"qmcolor" => "Black",
	"noqm" => "",
	"qmbg" => "#fec107",
	"qmradius" => "5",
	"qmsdx" => "2",
	"qmsdy" => "2",
	"qmsdcolor" => "#656565",
	"qmsd" => "on",
	"qmmt" => "10",
	"qmsdbdcolor" =>"",
	"disablecritpicto"=>"#fec107",
	"fulltextpicto"=>"#fec107"
);

$lemonzestbmsethemearray = array (
    "atb_font_color" => "white",
	"atb_bg_color" => "#c6c6c6",
	"atb_radius" => "5",
	"atb_margin_left" => "7",
	"atb_bg_color_hover" => "#5b5b5b",
	"atb_bg_border_color" => ""
);

?>